In [1]:
# Import libraries
import numpy as np
import pandas as pd

In [2]:
#Load datasets
data = pd.read_csv('Data_for_UCI_named.csv')


In [3]:
data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [4]:
# check for missing values
data.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [6]:
data.shape

(10000, 14)

In [7]:
data.columns

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4', 'stab', 'stabf'],
      dtype='object')

In [8]:
data.describe()

tau1          tau2          tau3          tau4            p1  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       5.250000      5.250001      5.250004      5.249997      3.750000   
std        2.742548      2.742549      2.742549      2.742556      0.752160   
min        0.500793      0.500141      0.500788      0.500473      1.582590   
25%        2.874892      2.875140      2.875522      2.874950      3.218300   
50%        5.250004      5.249981      5.249979      5.249734      3.751025   
75%        7.624690      7.624893      7.624948      7.624838      4.282420   
max        9.999469      9.999837      9.999450      9.999443      5.864418   

                 p2            p3            p4            g1            g2  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean      -1.250000     -1.250000     -1.250000      0.525000      0.525000   
std        0.433035      0.433035      0.433035      0.274256      0.274255   
min       -1.999891     -1.999945     -1.999926      0.050009      0.050053   
25%       -1.624901     -1.625025     -1.624960      0.287521      0.287552   
50%       -1.249966     -1.249974     -1.250007      0.525009      0.525003   
75%       -0.874977     -0.875043     -0.875065      0.762435      0.762490   
max       -0.500108     -0.500072     -0.500025      0.999937      0.999944   

                 g3            g4          stab  
count  10000.000000  10000.000000  10000.000000  
mean       0.525000      0.525000      0.015731  
std        0.274255      0.274255      0.036919  
min        0.050054      0.050028     -0.080760  
25%        0.287514      0.287494     -0.015557  
50%        0.525015      0.525002      0.017142  
75%        0.762440      0.762433      0.044878  
max        0.999982      0.999930      0.109403

In [9]:
#Check the distribution of the target variable
data['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [10]:
# Preprocessing
data = data.drop(columns=['stab'])
X = data.drop(columns=['stabf'])
y = data['stabf']


In [11]:
X

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376524  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  
1    -1.255012  0.413441  0.862414  0.562139  0.781760  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  
...        ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  

[10000 rows x 12 columns]

In [12]:
y

0       unstable
1         stable
2       unstable
3       unstable
4       unstable
          ...   
9995    unstable
9996      stable
9997      stable
9998    unstable
9999    unstable
Name: stabf, Length: 10000, dtype: object

In [13]:
data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [14]:
# Split data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)
y_train.value_counts()

unstable    5092
stable      2908
Name: stabf, dtype: int64

In [15]:
# Standard Scaling
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
#fit the data using the scaler
train_data = ss.fit_transform(x_train, y_train)
test_data = ss.transform(x_test)

In [16]:
# Random forest and Extra tree classifier
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=1)
rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)
y_pred

array(['unstable', 'unstable', 'stable', ..., 'stable', 'stable',
       'unstable'], dtype=object)

In [17]:
#Confusion Matrix, Precision-Recall, ROC curve and F1-score
# Confusion Matrix
from sklearn.metrics import recall_score,accuracy_score, precision_score, f1_score,confusion_matrix
from sklearn.metrics import classification_report
cnf_mat = confusion_matrix(y_test, y_pred, labels= ['stable', 'unstable'])
cnf_mat

array([[ 625,   87],
       [  55, 1233]], dtype=int64)

In [18]:
# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(classification_report(y_test, rf.predict(x_test)))


              precision    recall  f1-score   support

      stable       0.92      0.88      0.90       712
    unstable       0.93      0.96      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [61]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.929

In [19]:
from sklearn.ensemble import ExtraTreesClassifier
Extra_Trees = ExtraTreesClassifier(random_state=1)
Extra_Trees.fit(x_train, y_train)
etc_pred = Extra_Trees.predict(x_test)
etc_pred

array(['unstable', 'unstable', 'stable', ..., 'stable', 'unstable',
       'unstable'], dtype=object)

In [20]:
# confusion matrix
cnf_mat = confusion_matrix(y_test, etc_pred, labels= ['stable', 'unstable'])
cnf_mat

array([[ 606,  106],
       [  38, 1250]], dtype=int64)

In [64]:
print(classification_report(y_test, etc_pred))

              precision    recall  f1-score   support

      stable       0.94      0.85      0.89       712
    unstable       0.92      0.97      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [65]:
accuracy = accuracy_score(y_test, etc_pred)
accuracy

0.928

In [22]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators=[50,100,300,500,1000]
min_samples_split=[2, 3, 5, 7, 9]
min_samples_leaf=[1, 2, 4, 6, 8]
max_features=['auto', 'sqrt','log2',None]
hyperparameter_grid={'n_estimators': n_estimators,
                       'min_samples_leaf': min_samples_leaf,
                       'min_samples_split': min_samples_split,
                       'max_features': max_features}
print(hyperparameter_grid)

{'n_estimators': [50, 100, 300, 500, 1000], 'min_samples_leaf': [1, 2, 4, 6, 8], 'min_samples_split': [2, 3, 5, 7, 9], 'max_features': ['auto', 'sqrt', 'log2', None]}


In [23]:
#Create the base model tune
etc = ExtraTreesClassifier()
etc_random= RandomizedSearchCV(estimator =etc, param_distributions =hyperparameter_grid, random_state=1)
etc_random.fit(x_train, y_train)

RandomizedSearchCV(estimator=ExtraTreesClassifier(),
                   param_distributions={'max_features': ['auto', 'sqrt', 'log2',
                                                         None],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 3, 5, 7, 9],
                                        'n_estimators': [50, 100, 300, 500,
                                                         1000]},
                   random_state=1)

In [24]:
# Best parameter from fitting the random search
etc_random.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 8,
 'max_features': None}

In [25]:
etc_param = ExtraTreesClassifier(n_estimators=1000, min_samples_split=2,min_samples_leaf=8,max_features=None, random_state=1)
etc_param.fit(x_train, y_train)
etc_param_pred = etc_param.predict(x_test)
etc_param_pred

array(['unstable', 'unstable', 'stable', ..., 'stable', 'unstable',
       'unstable'], dtype=object)

In [26]:
#Confusion matrix
cnf_mat = confusion_matrix(y_test, etc_param_pred, labels=['stable', 'unstable'])
cnf_mat

array([[ 619,   93],
       [  53, 1235]], dtype=int64)

In [62]:
#classification report for hypertuning
print(classification_report(y_test, etc_param_pred))

              precision    recall  f1-score   support

      stable       0.92      0.87      0.89       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [63]:

accuracy = accuracy_score(y_test, etc_param_pred)
accuracy






0.927

In [53]:
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [54]:
xgb = XGBClassifier(random_state=1)
xgb.fit(x_train, y_train)
xgb_pred = xgb.predict(x_test)


In [55]:
# Confusion matrix
cnf_mat = confusion_matrix(y_test, xgb_pred, labels= ['stable', 'unstable'])
cnf_mat

array([[ 648,   64],
       [  45, 1243]], dtype=int64)

In [56]:
# Classification report
print(classification_report(y_test, xgb_pred))

              precision    recall  f1-score   support

      stable     0.9351    0.9101    0.9224       712
    unstable     0.9510    0.9651    0.9580      1288

    accuracy                         0.9455      2000
   macro avg     0.9430    0.9376    0.9402      2000
weighted avg     0.9453    0.9455    0.9453      2000



In [60]:
accuracy = accuracy_score(y_test, xgb_pred)
accuracy

0.9455

In [45]:
lgbm= LGBMClassifier(random_state=1)
lgbm.fit(x_train, y_train)
lgbm_pred = lgbm.predict(x_test)

In [46]:
# Confusion Matrix
cnf_mat = confusion_matrix(y_test, lgbm_pred, labels= ['stable', 'unstable'])
cnf_mat

array([[ 636,   76],
       [  49, 1239]], dtype=int64)

In [47]:
# Classification Report
print(classification_report(y_test, lgbm_pred))

              precision    recall  f1-score   support

      stable       0.93      0.89      0.91       712
    unstable       0.94      0.96      0.95      1288

    accuracy                           0.94      2000
   macro avg       0.94      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000



In [59]:
accuracy = accuracy_score(y_test, lgbm_pred)
accuracy

0.9375